# Generated by Django 2.2.1 on 2019-11-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='경도',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='대분류',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='소분류',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='시설명',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='위도',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='전화번호',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='facility',
            name='주소',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
